name: CI

on: [push, pull_request, release]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
        - {
            name: "Windows Latest MSVC",
            os: "windows-latest",
            build_type: "Release",
            cc: "cl",
            cxx: "cl",
            generators: "Visual Studio 17 2022",
            archiver: "7z a",
            artifact: "windows_msvc.7z"
          }
        - {
            name: "Ubuntu Latest GCC",
            os: "ubuntu-latest",
            build_type: "Release",
            cc: "gcc",
            cxx: "g++",
            generators: "Unix Makefiles",
            archiver: "tar czf",
            artifact: "ubuntu_gcc.7z"
          }
        - {
            name: "MacOS Latest Clang",
            os: "macos-latest",
            build_type: "Release",
            cc: "clang",
            cxx: "clang++",
            generators: "Unix Makefiles",
            archiver: "7za a",
            artifact: "macos_clang.7z"
          }

    steps:
      - uses: actions/checkout@v2

      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}

      - name: Install dependencies on Windows
        if: startsWith(matrix.config.os, 'windows')
        run: |
          .\.github\get-deps-msvc.ps1
          cmake --version

      - name: Install dependencies on Ubuntu
        if: startsWith(matrix.config.name, 'Ubuntu')
        run: |
          sudo apt update
          sudo apt install -y libsdl2-dev
          cmake --version
          gcc --version

      - name: Install dependencies on MacOS
        if: startsWith(matrix.config.os, 'macos')
        run: |
          brew install sdl2 p7zip
          cmake --version
          clang --version

      - name: Configure CMake
        shell: bash
        run: |
          mkdir build
          mkdir instdir
          cmake -S . -B . \
            -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} \
            -G "${{ matrix.config.generators }}" \
            -DENABLE_TOOLS=ON \
            -DCMAKE_INSTALL_PREFIX:PATH=instdir

      - name: Build
        shell: bash
        run: cmake --build . --config ${{ matrix.config.build_type }}

      - name: Test
        shell: bash
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html
        # for more detail
        run: ctest -C $BUILD_TYPE

      - name: Install & Strip
        shell: bash
        run: cmake --install . --strip

      - name: Pack
        shell: bash
        working-directory: instdir
        run: |
          ls -laR
          ${{ matrix.config.archiver }} ../${{ matrix.config.artifact }} .

      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          path: ./${{ matrix.config.artifact }}
          name: ${{ matrix.config.artifact }}

      - name: Upload release asset
        if: github.event_name == 'release' && (github.event.action == 'published' || github.event.action == 'created')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./${{ matrix.config.artifact }}
